name: rumba_go_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.0.0
  image_picker: ^1.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_image_compress: ^2.1.0
  geolocator: ^11.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  firebase_core: any
  firebase_auth: any
  mockito: ^5.4.2
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/logo_rumba_go.png
    - assets/google.png

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo/Exo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Exo/Exo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Exo/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo/Exo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Exo/Exo-Black.ttf
          weight: 900
        - asset: assets/fonts/Exo/Exo-Italic.ttf
          style: italic
        - asset: assets/fonts/Exo/Exo-BoldItalic.ttf
          weight: 700
          style: italic
