// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZpEdTXT1xk_BtBnix15dwbJrhr_B22M',
    appId: '1:136907631392:web:03dd594d65955258b34545',
    messagingSenderId: '136907631392',
    projectId: 'fire-rumba-go',
    authDomain: 'fire-rumba-go.firebaseapp.com',
    storageBucket: 'fire-rumba-go.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEqU1usv8luaykJ-UP2drFB8RWeJAjIII',
    appId: '1:136907631392:android:ea9e48ecda85dbb7b34545',
    messagingSenderId: '136907631392',
    projectId: 'fire-rumba-go',
    storageBucket: 'fire-rumba-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3YC7uszdlbOwZLAIeaKa7duA24CdC2Vc',
    appId: '1:136907631392:ios:0f27b4ec10a99333b34545',
    messagingSenderId: '136907631392',
    projectId: 'fire-rumba-go',
    storageBucket: 'fire-rumba-go.firebasestorage.app',
    androidClientId: '136907631392-uou1vdj38a7a1iv2ap3e0nb28nphm9e0.apps.googleusercontent.com',
    iosClientId: '136907631392-b297bvadiu8tpnd3pm98l9tca0ks9ru8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rumbaGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3YC7uszdlbOwZLAIeaKa7duA24CdC2Vc',
    appId: '1:136907631392:ios:0f27b4ec10a99333b34545',
    messagingSenderId: '136907631392',
    projectId: 'fire-rumba-go',
    storageBucket: 'fire-rumba-go.firebasestorage.app',
    androidClientId: '136907631392-uou1vdj38a7a1iv2ap3e0nb28nphm9e0.apps.googleusercontent.com',
    iosClientId: '136907631392-b297bvadiu8tpnd3pm98l9tca0ks9ru8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rumbaGoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJZpEdTXT1xk_BtBnix15dwbJrhr_B22M',
    appId: '1:136907631392:web:77d9ce2c9b92c21ab34545',
    messagingSenderId: '136907631392',
    projectId: 'fire-rumba-go',
    authDomain: 'fire-rumba-go.firebaseapp.com',
    storageBucket: 'fire-rumba-go.firebasestorage.app',
  );
}
